name: PR Build

on:
  pull_request:
    branches:
      - main # プルリクのターゲットブランチを指定
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        run: yarn install
        working-directory: project

      - name: Run build
        run: yarn build
        working-directory: project
